language: node_js

node_js:
  - "8.11.2"

sudo: required

#script: node_modules/karma/bin/karma start karma.conf.js --single-run

before_script:
  - npm install -g @angular/cli@1
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng build --prod

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - sabaliauskaspablo@gmail.com
    on_success: always # default: change
on_failure: always # default: always


