language: node_js

sudo: required

before_install:
  - nvm install 8.11.2
  - npm i -g npm@5.6.0
  #- export CHROME_BIN=chromium-browser
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - sabaliauskaspablo@gmail.com
    on_success: always # default: change
on_failure: always # default: always
